apiVersion: ovn.openstack.org/v1beta1
kind: OVNDBCluster
metadata:
  name: ovndbcluster-nb-sample
spec:
  replicas: 1
  logLevel: info
  storageRequest: 10G
  storageClass: local-storage
  dbType: NB
---
apiVersion: ovn.openstack.org/v1beta1
kind: OVNDBCluster
metadata:
  name: ovndbcluster-sb-sample
spec:
  replicas: 1
  logLevel: info
  storageRequest: 10G
  storageClass: local-storage
  dbType: SB
